version: '3'

services:
  db:
    container_name: task-db
    image: postgres:9.6
    networks:
      - api
    ports:
      - 5432:${DB_PORT}
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

  app:
    container_name: task-builder
    image: taskbuilder:v1.0
    restart: on-failure
    networks:
      - api
    depends_on:
      - db
    ports:
      - 8888:${PORT}
    environment:
       APPLICATION_NAME: task-builder-docker
       DB_HOST: db
       DB_USER: ${DB_USER}
       DB_PASSWORD: ${DB_PASSWORD}
       DB_PORT: ${DB_PORT}
       DB_NAME: ${DB_NAME}
       JWT_SECRET: ${JWT_SECRET}
       JWT_EXPIRES: ${JWT_EXPIRES}

networks:
  api: